# Variables
@baseUrl = http://localhost:4006/api/v1
@int = {{$randomInt 1000 9999}}
@authToken = {{login.response.body.message}}
@addedorderId = {{createorder.response.body.message.id}}

### Get all orders
GET {{baseUrl}}/orders/ HTTP/1.1
Authorization: {{authToken}}

### Add a order
# @name createorder
POST {{baseUrl}}/orders/ HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "order_date": "{{$datetime iso8601}}",
    "items":[    
        {"item_id":"{{items.response.body.message[0].id}}", "quantity":10},
        {"item_id":"{{items.response.body.message[1].id}}", "quantity":21},
        {"item_id":"{{items.response.body.message[2].id}}", "quantity":14},
        {"item_id":"{{items.response.body.message[3].id}}", "quantity":20}
    ],
    "status": false
}

### Get order details
GET {{baseUrl}}/orders/{{addedorderId}}
Authorization: {{authToken}}

### Update Specific order Details
PATCH {{baseUrl}}/orders/{{addedorderId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "order_date": "{{$datetime iso8601}}",
    "items":[    
        {"item_id":"{{items.response.body.message[1].id}}", "quantity":34},
        {"item_id":"{{items.response.body.message[2].id}}", "quantity":80}
    ],
    "status": true
}

### Delete a specific order
DELETE {{baseUrl}}/orders/{{addedorderId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

### Post login credentials to get a token
 # @name login
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "{{$dotenv LEVEL_ONE_NAME}}",
    "password": "{{$dotenv DEMO_PASSWORD}}"
}

### Get all items for picking random IDs
# @name items
GET {{baseUrl}}/items HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}